services:

  postgres:
    container_name: quiz_db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
  
  web:
    container_name: fastapi_backend
    build: .
    command: uvicorn --host 0.0.0.0 --port 8080 quiz.main:app --reload
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  database-data:

