"""Initial

Revision ID: 549390f5ccb6
Revises: adc9364442a3
Create Date: 2024-01-22 13:45:07.321073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549390f5ccb6'
down_revision: Union[str, None] = 'adc9364442a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('question', 'registered_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('registered_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('question', 'created_at')
    # ### end Alembic commands ###
