"""question unique True

Revision ID: 6c8ac88dd135
Revises: 81e8a400f601
Create Date: 2024-01-21 15:39:39.103066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8ac88dd135'
down_revision: Union[str, None] = '81e8a400f601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'question', ['question'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='unique')
    # ### end Alembic commands ###
